#!/bin/bash
#SBATCH --nodes=1
#SBATCH --job-name=PBdiactx
#SBATCH --time=00:40:00
#SBATCH --partition=gpu_shared
#SBATCH --gpus-per-node=1

source ~/.bashrc

module load 2019
source ${HOME}/projects/erp/venv/bin/activate

# Copy the input data to scratch space
cp -r ${HOME}/projects/erp/data ${TMPDIR}/data

bsz=4
n_sent=-1
ctx=dialogue_id
maxlen=1024
maxpos=56
dat=$(date +"%FT%T") 

cd ${HOME}/projects/erp

mkdir -p /project/dmg_data/erp/results_conll/pb_gpt2-ft_${ctx}_${n_sent}_${maxlen}_${maxpos}_${dat}

#python3 -m torch.distributed.launch --nproc_per_node=1 --nnodes=1 --node_rank=0 
python3 src/contextualised_entropy.py \
	--data_path /project/dmg_data/erp/data_clean/PB/analysis.csv \
	--out_path /project/dmg_data/erp/results_conll/pb_gpt2-ft_${ctx}_${n_sent}_${maxlen}_${maxpos}_${dat} \
	--per_gpu_batch_size $bsz \
	--seed 0 \
	--n_sent ${n_sent} \
	--model_name gpt2 \
	--model_path /project/dmg_data/erp/models/pb/gpt2_gpt2_bsz2_lr0.0001_epochs20_2021-06-02T03:30:42/ \
	--context_field ${ctx} \
	--max_seq_len ${maxlen} \
	--add_special_tokens \
	--max_position ${maxpos} \
	&> out_conll/10june/pb_gpt2-ft_${ctx}_${n_sent}_${maxlen}_${maxpos}_${dat}


