#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --job-name=pb_h
#SBATCH --time=1:00:00
#SBATCH --output=slurm_output/%A.out
# https://servicedesk.surfsara.nl/wiki/display/WIKI/Lisa+usage+and+accounting
echo "${SLURM_JOB_ID}"
date

source ${HOME}/.bashrc
module purge
module load 2022
module load Anaconda3/2022.05
source "$(conda info --base)/etc/profile.d/conda.sh"
conda deactivate
conda activate stat-gen-eval-3.10

export ROOT="/home/${USER}/projects/uid-dialogue/"

bsz=4
n_sent=-1
maxlen=1024


mkdir -p results/pb_gpt2-ft_${n_sent}_${maxlen}_$(date +"%FT%T")

#python3 -m torch.distributed.launch --nproc_per_node=1 --nnodes=1 --node_rank=0 
python3 src/decontextualised_entropy.py \
	--data_path /scratch-shared/mariog/data_clean/PB/analysis.csv \
	--out_path results/pb_gpt2-ft_${n_sent}_${maxlen}_$(date +"%FT%T")  \
	--per_gpu_batch_size $bsz \
	--seed 0 \
	--n_sent ${n_sent} \
	--model_name gpt2 \
	--model_path /scratch-shared/mariog/models/pb_gpt2-ft \
	--max_seq_len ${maxlen} \
	&> out/pb_gpt2-ft_${n_sent}_${maxlen}_$(date +"%FT%T")
